### ISSUE TITLE
Check visibility of old expressions

### ISSUE THREAD

**Issue by noahknapen** [fsc4j/fsc4j#37] opened 2023-06-07 10:59 UTC
In the `s4jie2TestSuite.java`, consider the following test case:

```java
testCompile("throws_may_throw_resolve_error", false, "",
	    		"----------\n"
	    		+ "1. ERROR in SOURCE_FILE_FULL_PATH (at line 8)\n"
	    		+ "	* @throws IllegalArgumentException | 10000 <= y\n"
	    		+ "	                                              ^\n"
	    		+ "y cannot be resolved to a variable\n"
	    		+ "----------\n"
	    		+ "2. ERROR in SOURCE_FILE_FULL_PATH (at line 10)\n"
	    		+ "	*    | 10000 <= z\n"
	    		+ "	                ^\n"
	    		+ "The field Foo.z is not visible\n"
	    		+ "----------\n"
	    		+ "3. ERROR in SOURCE_FILE_FULL_PATH (at line 11)\n"
	    		+ "	* @throws IlegalArgumentExeption | true\n"
	    		+ "	          ^^^^^^^^^^^^^^^^^^^^^^\n"
	    		+ "IlegalArgumentExeption cannot be resolved to a type\n"
	    		+ "----------\n"
	    		+ "4. ERROR in SOURCE_FILE_FULL_PATH (at line 15)\n"
	    		+ "	*    | 5000 <= y\n"
	    		+ "	               ^\n"
	    		+ "y cannot be resolved to a variable\n"
	    		+ "----------\n"
	    		+ "5. ERROR in SOURCE_FILE_FULL_PATH (at line 16)\n"
	    		+ "	* @may_throw IllegalArgumentException | 5000 <= z \n"
	    		+ "	                                                ^\n"
	    		+ "The field Foo.z is not visible\n"
	    		+ "----------\n"
	    		+ "5 problems (5 errors)\n");
```

This test was made prior to the verification of `@may_throw` clauses. In the current implementation, `@may_throw` clauses are converted to an `OldExpression`, which has no visibility checks implemented, resulting in failure of this test. as the fifth error of the current test case is not discovered in the current implementation.

**Comment by btj** [comment] 2024-04-10 08:56
Duplicate of #30

**Closed by btj** 2024-04-10 08:56 UTC
