### ISSUE TITLE
Expression referring to a static method before object's constructor is executed causes an error

### ISSUE THREAD

**Issue by vlad2305m** [fsc4j/fsc4j#42] opened 2024-04-15 15:41 UTC
```java
public class Main {
	public static void main(String[] args) {
	    Main main = new Main();
	}
	/**
	 * @pre | check()
	 */
	public Main() {}
	public static boolean check() { return true; }
}
```
Causes error:
```
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	This expression refers to an object before its constructor is executed, which is not allowed

	at test.Main.<init>(Main.java:13)
	at test.Main.main(Main.java:10)

**Comment by btj** [comment] 2024-04-15 18:29
Thanks for reporting! Duplicate of #41. Fixed in 0.8.3.

**Closed as not planned by btj** 2024-04-15 18:29 UTC
